language: r
warnings_are_errors: true

cache: packages

sudo: required

r_packages:
  - caret
  - e1071

r_github_packages:
  - jimhester/covr
  - frehbach/EventDetectR

after_success:
  - Rscript -e 'library(covr);codecov()'
